on:
  pull_request:
  push:
    branches: [main]

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          source-url: https://nuget.pkg.github.com/xt0rted/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: .NET build
        run: dotnet build --configuration Release
